
# html lang
language: en

# header
site_brand_name: SHH

logo_image:
  enable: false
  image_path: /logo.png # path to your logo image

menu:
  Home: /
  Projects: /categories/gallery/
  Blogs: /archives/
  About Me: /About-Me

# stylesheets loaded in the <head>
stylesheets:
- /css/style.css

# scripts loaded in the end of the body
scripts:
- /js/frame.js

# favicon
favicon: /favicon.ico

date_format: MMM D, YYYY

# profile
profile:
  title: Hi, this is Haohai(Haines) Shi, 石昊海.
  body:
    - A senior student majoring in Physics at Zhejiang University.
    - Currently working at Prof. Haohua Wang's group, doing research on superconducting quantum computing and quantum simulation.
  image: /img/Shaw_Circular.png
  

  links:
    About Me: /About-Me/
    Blogs: /archives/
    Projects: /categories/gallery/
    📧shawhaines@zju.edu.cn: mailto:shawhaines.zju.edu.cn
    Github: https://github.com/ShawHaines

# footer
footer:
  copyright_info:
    enable: true
    author: Haohai(Haines) Shi 石昊海

  powered_by: # Powered by Hexo & Frame
    enable: true

  other_info:
    enable: false
    content:

# color mode: default / classic / dark
color_mode: default

# mathjax setting
# note: need to install the hexo plugin for math: https://github.com/hexojs/hexo-math
mathjax_enable: true

# comments: support disqus and valine
valine: # valine setup guide: https://valine.js.org/quickstart.html
  enable: false
  appId: # Your valine app Id
  appKey: # Your valine app Key
  lang: 'en'
  placeholder: 'Say something'
  avatar: 'mp'
  meta: ['nick', 'mail']

disqus: # disqus setup guide: https://help.disqus.com/en/articles/1717056-publisher-quick-start-guide
  enable: false
  disqus_url: # your diqsuq url or shortname
  language: 'en'